[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_API_URL = "https://e-commerce-q2x2.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200